### ISSUE TITLE
[BUG] Media Extensions not Saved on 'Save' button click

### ISSUE THREAD

**Issue by HS-ghub** [JerloPH/HomeCinema#8] opened 2021-06-07 08:20 UTC
I have a large collection of Blu-rays and DVDs stored as ISO images.
They're set to open in VLC player on double-click. It would be great if I can add them into HomeCinema database.

I tried adding ISO extension in the file settings but the setting is not saved and nothing changes on program restart.

There's also a typo in the settings menu: The "CANCEL" button displays as "CANCE".

**Comment by JerloPH** [comment] 2021-06-07 10:31
First, I should prolly include a report format but for now, include your App version.

On the issues,

1. This is a "whoopsie" moment for me. Turns out, I didn't implement the Save on Media Extensions properly. This should be fixed on the next release.
2.  This is prolly caused by difference in resolutions but I will try to reduce the font size to fit the button across different resolutions.
 
Keep me posted after the next release to see if these issues are fixed

**Comment by JerloPH** [comment] 2021-06-12 06:18
New release addressing the issue. Will close now.

**Closed as completed by JerloPH** 2021-06-12 06:18 UTC
Labels: bug
